iftopalmas/sistemas-viagem

sistema-companhia-aerea/src/main/resources/application.properties

Configurar acesso ao postgres no application.properties do sistema-companhia-aerea
Close #7

feat(companhia-aerea): configurar postgres no application.properties

---

sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/Cidade.java
sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/Estado.java
sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/Cidade.java
sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/Estado.java

Cria classes Estado e Cidade para o sistema aéreo e veículos (#13, #16)

---

sistema-hotelaria/src/main/java/br/edu/ifto/sistemahotelaria/entidades/Cidade.java
sistema-hotelaria/src/main/java/br/edu/ifto/sistemahotelaria/entidades/Estado.java

Cria classes Estado e Cidade para o sistema hotelaria #14

---

.gitignore
sistema-agencia-viagem/src/main/resources/application.properties

Configurar acesso ao postgres no application.properties do sistema-agencia-viagens #8

---

sistema-hotelaria/.env.dist
sistema-hotelaria/.env.example
sistema-hotelaria/.gitignore
sistema-hotelaria/src/main/resources/application.properties

Configurar acesso ao postgres no application.properties do sistema-hotelaria #10

---

sistema-locadora-veiculo/pom.xml

Issue 36 - Adicionar biblioteca Open API e testar acesso à swagger UI ao sistema de veículos

---

sistema-hotelaria/pom.xml

Close #35 
Para averiguar funcionamento, segue a imagem

Adicionando a biblioteca Open API

---

sistema-companhia-aerea/pom.xml
sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/entidades/Aviao.java
sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/entidades/MarcaAviao.java
sistema-hotelaria/pom.xml

#39 Adicionando as classes Aviao e MarcaAviao ao sistema-aereo

---

sistema-agencia-viagem/pom.xml
sistema-companhia-aerea/pom.xml
sistema-hotelaria/pom.xml
sistema-locadora-veiculo/pom.xml

ISSUE#57, Lombok adicionado nos 4 projetos

---

sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/entidades/Cidade.java
sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/entidades/Cliente.java
sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/entidades/Endereco.java
sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/entidades/Funcionario.java
sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/entidades/Pessoa.java
sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/entidades/PessoaFisica.java

Close #53
Faltando a conexão com o banco de dados para testar a criação das tabelas

Issue #53 Hierarquia pessoa fisica

---

sistema-companhia-aerea/pom.xml
sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/model/entity/Aeroporto.java
sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/model/entity/CompanhiaAerea.java

Criar entidade (classe) Aeroporto e CompanhiaAerea #52

---

sistema-companhia-aerea/pom.xml
sistema-companhia-aerea/src/main/resources/application.properties

Issue 37 - Adicionar biblioteca Open API ao sistema aéreo e testar acesso à swagger UI

---

sistema-companhia-aerea/pom.xml
sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/model/Cidade.java
sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/model/Cliente.java
sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/model/ContatoSeguranca.java
sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/model/Endereco.java
sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/model/Estado.java
sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/model/GrauParentesco.java
sistema-companhia-aerea/src/main/resources/import.sql

#28 Criar entidade classe cliente e relacionadas no sistema aéreo

---

sistema-agencia-viagem/pom.xml
sistema-agencia-viagem/src/main/java/br/edu/ifto/sistemaagenciaviagem/entidades/Cidade.java
sistema-agencia-viagem/src/main/java/br/edu/ifto/sistemaagenciaviagem/entidades/Cliente.java
sistema-agencia-viagem/src/main/java/br/edu/ifto/sistemaagenciaviagem/entidades/Endereco.java
sistema-agencia-viagem/src/main/java/br/edu/ifto/sistemaagenciaviagem/entidades/Estado.java

#27 Criar entidade (classe) cliente e relacionados no sistema de agencia

---

sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/model/Cliente.java
sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/model/Pessoa.java
sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/model/PessoaFisica.java
sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/model/Piloto.java
sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/model/entity/Aeroporto.java

#51 Criar hierarquia de herança para as classes de Pessoa no sistema aéreo

---

sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/model/Aeroporto.java
sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/model/Aviao.java
sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/model/Cidade.java
sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/model/CompanhiaAerea.java
sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/model/ContatoSeguranca.java
sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/model/Endereco.java
sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/model/Estado.java
sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/model/GrauParentesco.java
sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/model/MarcaAviao.java
sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/model/Voo.java

Padronizar os pacotes

---

sistema-companhia-aerea/pom.xml
sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/repository/EstadoRepository.java

Criar API REST para gerenciar Estados no sistema aéreo #78

---

sistema-agencia-viagem/src/main/java/br/edu/ifto/sistemaagenciaviagem/entidades/Cidade.java
sistema-agencia-viagem/src/main/java/br/edu/ifto/sistemaagenciaviagem/entidades/Cliente.java
sistema-agencia-viagem/src/main/java/br/edu/ifto/sistemaagenciaviagem/entidades/Endereco.java
sistema-agencia-viagem/src/main/java/br/edu/ifto/sistemaagenciaviagem/entidades/Estado.java
sistema-hotelaria/src/main/java/br/edu/ifto/sistemahotelaria/entidades/Cidade.java
sistema-hotelaria/src/main/java/br/edu/ifto/sistemahotelaria/entidades/Cliente.java
sistema-hotelaria/src/main/java/br/edu/ifto/sistemahotelaria/entidades/Estado.java
sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/entidades/Cidade.java
sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/entidades/Endereco.java
sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/entidades/Estado.java
sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/entidades/Funcionario.java
sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/entidades/Pessoa.java
sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/entidades/PessoaFisica.java

#64 Remover os métodos getters e setters e adicionar anotações `@Getter` e `@Setter`

---

sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/repository/MarcaAviaoRepository.java

Criar API REST para gerenciar MarcaAviao no sistema aéreo #83

---

sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/repository/CidadeRepository.java

Criar API REST para gerenciar Cidades no sistema aéreo #77

---

sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/repository/AviaoRepository.java

Criar API REST para gerenciar Aviões no sistema aéreo #79

---

sistema-agencia-viagem/.env.example
sistema-agencia-viagem/pom.xml
sistema-agencia-viagem/src/main/resources/application.properties
sistema-companhia-aerea/.env.example
sistema-companhia-aerea/pom.xml
sistema-companhia-aerea/src/main/resources/application.properties
sistema-hotelaria/.env.dist
sistema-hotelaria/.env.example
sistema-hotelaria/pom.xml
sistema-hotelaria/src/main/resources/application.properties
sistema-locadora-veiculo/.env.example
sistema-locadora-veiculo/pom.xml
sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/entidades/Cliente.java
sistema-locadora-veiculo/src/main/resources/.env.example
sistema-locadora-veiculo/src/main/resources/application.properties

Fix #111  #115

---

sistema-agencia-viagem/.editorconfig
sistema-companhia-aerea/.editorconfig
sistema-hotelaria/.editorconfig
sistema-locadora-veiculo/.editorconfig

- Insere configurações em cada projeto para suportar novas formatações
Fix #114

Fix #114 - Insere configurações de formatação

---

sistema-hotelaria/src/main/resources/import.sql

Close #124 Atualização do import.sql.

---

sistema-companhia-aerea/src/main/java/br/edu/ifto/sistemacompanhiaaerea/repository/VooRepository.java

Issue #112

---

sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/entidades/Cliente.java
sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/entidades/FormaPagamento.java
sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/entidades/Reserva.java
sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/repositories/FormaPagamentoRepository.java
sistema-locadora-veiculo/src/main/java/br/edu/ifto/sistemalocadoraveiculo/repositories/ReservaRepository.java

Close #133 
- Altera tipo de dado do id de Cliente

Close #133
